# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  PAYLOAD: "payload={\"channel\": \"#mobile\", \"username\": \"Gitlab podspec deplyment\", \"text\": \"$SLACK_MESSAGE\", \"icon_emoji\": \"$SLACK_EMOJI\"}"
  HOOK: https://hooks.slack.com/services/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

before_script:
  - rbenv install --skip-existing
  - gem install bundler --force
  - ruby -v
  - which ruby
  - bundle install --path vendor/bundle

stages:
  - deploy
  - notify
   
updatePodSpec:
  stage: deploy
  only:
      - pipelines
  script:
    - git checkout master
    - curl --header -F "job-token=$CI_JOB_TOKEN" "http://gitlab.bluedot.io/api/v4/projects/1/jobs/artifacts/${REF_NAME}/download?job=build-release-framework-xcode-default" >> artifacts.zip
    - unzip artifacts.zip
    - rm -rf PointSDK/BDPointSDK.framework
    - cp -r build/artifacts/framework-Release/Xcode9.3/BDPointSDK.framework PointSDK/BDPointSDK.framework
    - sed -i '' -E "s/(s.version = \").*(\")/\1${VERSION}\2/" BluedotPointSDK.podspec
    - git add BluedotPointSDK.podspec PointSDK/BDPointSDK.framework
    - git commit -m "update version to ${VERSION}"
    - git tag ${VERSION}
    - git push -f -ff origin master & git push origin ${VERSION}
    - git remote -v | grep -q github && echo "github remote is configured" || git remote add github git@github.com:Bluedot-Innovation/PointSDK-iOS.git
    - git push -f -ff origin github & git push github ${VERSION}
    - pod trunk push BluedotPointSDK.podspec

.notification_template: &notification_job
  stage: notify
  only:
    - pipelines
  script:
    - curl -X POST --data-urlencode "$PAYLOAD" "$HOOK"


notifySuccess:
  variables:
    SLACK_MESSAGE: "BluedotPointSDK v.${VERSION}(${BUILD_NUMBER}) has been deployed to cocoapods. https://cocoapods.org/pods/BluedotPointSDK"
    SLACK_EMOJI: ":green_apple:"
  when: on_success
  <<: *notification_job
  
notifyFailure:
  variables:
    SLACK_MESSAGE: "Cocoapods deployment failed. ${CI_PROJECT_URL}"
    SLACK_EMOJI: ":apple:"
  when: on_failure
  <<: *notification_job

    