# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - rbenv install --skip-existing
  - gem install bundler --force
  - ruby -v
  - which ruby
  - bundle install --path vendor/bundle
   
updatePodSpec:
  stage: deploy
  only:
      - pipelines
  script:
    - git checkout master
    - curl --header -F "job-token=$CI_JOB_TOKEN" "http://gitlab.bluedot.io/api/v4/projects/1/jobs/artifacts/master/download?job=build-release-framework-xcode-default" >> artifacts.zip
    - unzip artifacts.zip
    - rm -rf PointSDK/BDPointSDK.framework
    - cp -r build/artifacts/framework-Release/Xcode9.3/BDPointSDK.framework PointSDK/BDPointSDK.framework
    - sed -i '' -E "s/(s.version = \").*(\")/\1${VERSION}\2/" BluedotPointSDK.podspec
    - git add BluedotPointSDK.podspec PointSDK/BDPointSDK.framework
    - git commit -m "update version to ${VERSION}"
    - git tag ${VERSION}
    - git push -f -ff origin master & git push origin ${VERSION}
    - git remote -v | grep -q github && echo "github remote is configured" || git remote add github git@github.com:Bluedot-Innovation/PointSDK-iOS.git
    - git push -f -ff origin github & git push github ${VERSION}
    - pod trunk push BluedotPointSDK.podspec