# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  SUCCESS: "BluedotPointSDK v.$VERSION($BUILD_NUMBER) has been deployed to cocoapods. https://cocoapods.org/pods/BluedotPointSDK"
  FAULURE: "Cocoapods deployment failed. http://gitlab.bluedot.io/apple/PointSDK-podspec"
  SUCCESS_PAYLOAD: "payload={\"channel\": \"#mobile\", \"username\": \"Gitlab podspec deplyment\", \"text\": \"$SUCCESS\", \"icon_emoji\": \":green_apple:\"}"
  FAILURE_PAYLOAD: "payload={\"channel\": \"#mobile\", \"username\": \"Gitlab podspec deplyment\", \"text\": \"$FAULURE\", \"icon_emoji\": \":apple:\"}"
  HOOK: https://hooks.slack.com/services/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

stages:
  - deploy
  - notify
   
updatePodSpec:
  tags:
    - xcode9
  stage: deploy
  only:
    - pipelines
    - triggers
  before_script:
    - rbenv install --skip-existing
    - gem install bundler --force
    - ruby -v
    - which ruby
    - bundle install --path vendor/bundle

    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$ID_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$GITLAB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    
    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    - git config --global user.email 'devops@bluedot.io'
    - git config --global user.name 'Bluedot'
    
    - git reset --hard
    - git clean -fd
    
    #
    # Set origin remote to gitlab ssh endpoint
    # Set github remote to github ssh endpoint
    #
    - git remote set-url origin git@gitlab.bluedot.io:apple/PointSDK-podspec.git
    - git remote -v | grep -q github && echo "github remote is configured" || git remote add github git@github.com:Bluedot-Innovation/PointSDK-iOS.git
  script:
    #
    # Aa we want to make a public release, make all changes on master branch, as it will be pushed to Github remote
    #
    - git checkout master
    #
    # Download the latest artifact from the merged branch' pipeline.
    # Replace current framework with the latest build.
    #
    - curl --header -F "job-token=$CI_JOB_TOKEN" "http://gitlab.bluedot.io/api/v4/projects/1/jobs/artifacts/${REF_NAME}/download?job=build-release-framework-xcode-default" >> artifacts.zip
    - unzip artifacts.zip
    - rm -rf PointSDK/BDPointSDK.framework
    - cp -r build/artifacts/framework-Release/Xcode9.3/BDPointSDK.framework PointSDK/BDPointSDK.framework
    #
    # Update version number in podspec.
    #
    - sed -i '' -E "s/(s.version = \").*(\")/\1${VERSION}\2/" BluedotPointSDK.podspec
    #
    # Stage new framewrk and updated podspec.
    # Create a version tag
    #
    - git add BluedotPointSDK.podspec PointSDK/BDPointSDK.framework
    - git commit -m "update version to ${VERSION}"
    - git tag ${VERSION}
    #
    # Push changes to origin and github remotes.
    # Thus cocopods will be able to get the latest build and two remotes will be in sync.
    #
    - git push -f origin master & git push origin ${VERSION}
    - git push -f github master & git push github ${VERSION}
    #
    # Update cocoapods trunk.
    #
    - pod trunk push BluedotPointSDK.podspec

.notification_template: &notification_job
  tags:
    - xcode9
  stage: notify
  only:
    - pipelines
    - triggers

notifySuccess:
  when: on_success
  <<: *notification_job
  script:
    - curl -X POST --data-urlencode "$SUCCESS_PAYLOAD" "$HOOK"
  
notifyFailure:
  when: on_failure
  <<: *notification_job
  script:
    - curl -X POST --data-urlencode "$FAILURE_PAYLOAD" "$HOOK"

